services:
  content_creator:
    build: .
    container_name: Content_creator
    deploy:
      resources:
        limits:
          memory: 3G
    env_file:
      - .env
    volumes:
      - .:/app        # Sincroniza tu carpeta local con /app en tiempo real
    command: python main.py
    restart: unless-stopped

  comfyui:
    build:
      context: .
      dockerfile: Dockerfile.comfyui
    container_name: ComfyUI_Server
    command: python main.py --listen 0.0.0.0 --port 8188 --lowvram
    ports:
      - "8188:8188"
    volumes:
      - ./data/comfyui/models:/comfyui/models
      - ./data/comfyui/output:/comfyui/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped